#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (c) 2026 OShell contributors
"""Generate the optional ambiguous-width table from pinned Unicode 17 data."""
import argparse, hashlib
from pathlib import Path
URL = 'https://www.unicode.org/Public/17.0.0/ucd/EastAsianWidth.txt'
SHA256 = 'ea7ce50f3444a050333448dffef1cadd9325af55cbb764b4a2280faf52170a33'
p = argparse.ArgumentParser(); p.add_argument('input', type=Path)
p.add_argument('--output', type=Path, default=Path(__file__).resolve().parent.parent/'Vendor/SwiftTerm/Sources/SwiftTerm/AmbiguousWidthData.swift')
a = p.parse_args(); data = a.input.read_bytes()
if hashlib.sha256(data).hexdigest() != SHA256: raise SystemExit('Expected the pinned Unicode 17 EastAsianWidth.txt from ' + URL)
ranges = []
for line in data.decode().splitlines():
    fields = line.split('#')[0].strip().split(';')
    if len(fields) != 2 or fields[1].strip() != 'A': continue
    ends = fields[0].strip().split('..'); start, end = int(ends[0],16), int(ends[-1],16)
    if ranges and start == ranges[-1][1] + 1: ranges[-1] = (ranges[-1][0], end)
    else: ranges.append((start,end))
text = '// Generated by scripts/generate-ambiguous-width.py; do not edit manually.\n'
text += '// Unicode 17.0.0 data © Unicode, Inc. SPDX-License-Identifier: Unicode-3.0\n'
text += '// License: THIRD_PARTY_NOTICES.txt. Source: ' + URL + '\n'
text += '// SHA256: ' + SHA256 + '\nstruct AmbiguousWidthData {\n    static let ranges: [UnicodeUtil.LH] = [\n'
text += ''.join(f'        .init(lo: 0x{lo:X}, hi: 0x{hi:X}),\n' for lo,hi in ranges)
text += '    ]\n}\n'; a.output.write_text(text)
print(f'Generated {len(ranges)} ranges')
